### ISSUE TITLE
About the debugging of your code.

### ISSUE THREAD

**Issue by MarkYangjiayi** [boluoweifenda/WAGE#12]
Hi,

Your work is amazing and I am currently trying to apply it to another area. This question might be silly but here it goes: how do you actually debug your code? 

The thing is that I'm a bit new to Tensorflow and added a lot of layers and components to your code, and sometimes the error and loss acts weird. I noticed your Option.debug but is not really sure how to use it. Do I have to saved these results somewhere and look at them later? Thanks.

**Comment by boluoweifenda** [comment]
@MarkYangjiayi 
Actually, it is a good question.
I use Pycharm debug mode and set the Option.debug in my code to True to debug the dataflow.
After setting a break point in the training cycle 
[https://github.com/boluoweifenda/WAGE/blob/master/source/Top.py#L141](url)
and running for several iterations, you can check the value of W, A, G, E that are defined as W_q, H, gradH, gradW_q, respectively.
[https://github.com/boluoweifenda/WAGE/blob/master/source/Top.py#L138](url)
Or you can show more data by adding it to the tensorflow graph and get the value by session.run() 
My method seems slightly clumsy but it fullfilled my requirements at that time.
Now you can use more elegant methods such as tensorflow eager execution or tensorBoard.
Good luck !

**Comment by MarkYangjiayi** [comment]
@boluoweifenda Thanks for the reply!
