### ISSUE TITLE
python Top.py has an error  from tensorflow. math_ops.maximum(0, queue.size() - min_after_dequeue)) *

### ISSUE THREAD

**Issue by libingict** [boluoweifenda/WAGE#3]
HI, dear authors,

Thanks for you execellent work. I am trying to run your code at my platform. But an error occurs.

Here is the error output:
> Traceback (most recent call last):
>   File "Top.py", line 170, in <module>
>     main()
>   File "Top.py", line 50, in main
>     getData.loadData(Option.dataSet,batchSize,numThread)
>   File "/home/xxxx/WAGE/source/getData.py", line 26, in loadData
>     trainX, trainY = data2Queue(numpyTrainX, numpyTrainY, batchSize,numThread, True,True)
>   File "/home/xxxx/WAGE/source/getData.py", line 60, in data2Queue
>     seed=seed)
>   File "/home/xxxx/anaconda3/envs/tensorflow/lib/python2.7/site-packages/tensorflow/python/training/input.py", line 1301, in shuffle_batch
>     name=name)
>   File "/home/xxxx/anaconda3/envs/tensorflow/lib/python2.7/site-packages/tensorflow/python/training/input.py", line 835, in _shuffle_batch
>     math_ops.maximum(0, queue.size() - min_after_dequeue)) *
> 
It seems like that "queue.size()" returns a Tensor dtype.

I did not do any change on Option.py. Here is the output of  Option.py. 
> import time
> import tensorflow as tf
> 
> debug = False
> Time = time.strftime('%Y-%m-%d', time.localtime())
> Notes = 'temp'
> GPU = [0]
> batchSize = 128
> dataSet = 'CIFAR10'
> 
> loadModel = None
> saveModel = '../model/' + Time + '(' + Notes + ')' + '.tf'
> 
> bitsW = 2  # bit width of we ights
> bitsA = 8  # bit width of activations
> bitsG = 8  # bit width of gradients
> bitsE = 8  # bit width of errors
> 
> bitsR = 16  # bit width of randomizer
> 
> lr = tf.Variable(initial_value=0., trainable=False, name='lr', dtype=tf.float32)
> lr_schedule = [0, 8, 200, 1,250,1./8,300,0]
> 
> L2 = 0
> 
> lossFunc = 'SSE'
> optimizer = tf.train.GradientDescentOptimizer(1)  # lr is controlled in Quantize.G
> seed = None
> sess = None
> W_scale = []

Here is the python, tensorflow, nvcc version.
```
python --version
Python 2.7.15 :: Anaconda, Inc.
```
```
tf.__version__
'1.6.0'
```
```
tqdm --version
4.23.2
```
```
nvcc --version
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2017 NVIDIA Corporation
Built on Fri_Sep__1_21:08:03_CDT_2017
Cuda compilation tools, release 9.0, V9.0.176
```
Did I do anything wrong with the configuration or the requirements? Looking forward to hear from you.  Thanks in advance.

**Comment by boluoweifenda** [comment]
@libingict   Have you downloaded and generated the CIFAR10 dataset? Following this 
`cd dataSet/
python CIFAR10.py`

**Comment by libingict** [comment]
@boluoweifenda Thanks for your reply. I have used the cmd `cd dataSet/ python CIFAR10.py `to download cifar10 data set.

here are my dataSet. 
> ls dataSet/* -lth
> -rw-rw-r-- 1 xxxx xxxx 177M May  3 10:34 dataSet/CIFAR10.npz
> -rw-rw-r-- 1 xxxx xxxx 1.9K May  3 10:34 dataSet/CIFAR10.py
> -rw-rw-r-- 1 xxxx xxxx 163M May  2 14:32 dataSet/cifar-10-python.tar.gz
> 
> dataSet/cifar-10-batches-py:
> total 178M
> -rw-r--r-- 1 xxxx xxxx  88 Jun  4  2009 readme.html
> -rw-r--r-- 1 xxxx xxxx 158 Mar 31  2009 batches.meta
> -rw-r--r-- 1 xxxx xxxx 30M Mar 31  2009 data_batch_4
> -rw-r--r-- 1 xxxx xxxx 30M Mar 31  2009 data_batch_1
> -rw-r--r-- 1 xxxx xxxx 30M Mar 31  2009 data_batch_5
> -rw-r--r-- 1 xxxx xxxx 30M Mar 31  2009 data_batch_2
> -rw-r--r-- 1 xxxx xxxx 30M Mar 31  2009 data_batch_3
> -rw-r--r-- 1 xxxx xxxx 30M Mar 31  2009 test_batch

**Comment by boluoweifenda** [comment]
@libingict 
It seem to be the input pipeline problem. I test the code again with tensorflow version 1.4 and no error occurs. 
Could you enter the debug mode and check the variable sampleX_  in this line?
    [https://github.com/boluoweifenda/WAGE/blob/master/source/getData.py#L52](url)
For me, sampleX_ is a tensor with shape (3, 32, 32)
Also dataX is a numpy array with shape (50000, 32, 32, 3)
Please check if you have read the dataset correctly and the parameters of tf.train.shuffle_batch are normal.
It wouldn't take too much time to make it work if you are familiar with tensorflow. 
Or you can just use placeholder + feed_dict to provide input batches, following this
https://www.tensorflow.org/programmers_guide/datasets
Good luck!

**Comment by libingict** [comment]
@boluoweifenda Thanks for your kind explanation. It seems like the error is due to the inappropriate tensorflow version. After I downgrade the version of tf to 1.4, and also reinstall cudnn and cuda toolkit, the codes can run well.  
Thank you again.

**Comment by boluoweifenda** [comment]
@libingict  Thanks for your version test. I will update tensorflow to see what's new.
