### ISSUE TITLE
y = Q(C(x, bitsW), bitsW)?

### ISSUE THREAD

**Issue by YanWang2014** [boluoweifenda/WAGE#4]
According to equ 3, should it be y = C(Q(x, bitsW), bitsW)?

**Comment by boluoweifenda** [comment]
@YanWang2014  
Yes, it should be y = C(Q(x, bitsW), bitsW), which is equivalent to Q(C(x, bitsW), bitsW). 
And in order to skip the gradient of Q(x) in backprop and speed up training, I place clip(x) in the first to make the codes neat

**Comment by YanWang2014** [comment]
Thanks for the explanation!
