### ISSUE TITLE
Should the data type of MNIST be int8?

### ISSUE THREAD

**Issue by suikammd** [boluoweifenda/WAGE#5]
I am trying to implement results of MNIST in your paper. Since the data type of MNIST is float32, should I transfer it to int8?  And I want to know what the meaning of "average accuracy of 10" in you paper at 4.1 IMPLEMENT DETAILS .

**Comment by boluoweifenda** [comment]
@suikammd     
All input data are quantize to INT8 in this line https://github.com/boluoweifenda/WAGE/blob/master/source/NN.py#L24
And we run the training process for 10 times and average the best accuracy in each cycle.
Hope these will help you, good luck!

**Comment by suikammd** [comment]
Oh, so I don't need to quantize the input data myself. I tranfered the type from float32 to int8 wthout using the methods you provided.
Thanks a lot!
