### ISSUE TITLE
Where is the code for alpha in eq8?

### ISSUE THREAD

**Issue by jxgu1016** [boluoweifenda/WAGE#7]
In ```Quantize.A()```, I cannot find the part for alpha which the eq8 has. As far as I can see, the alpha is always **1**, so you simply omitted it. Am I correct?

**Comment by boluoweifenda** [comment]
@jxgu1016 
We move the scale to the QW, it is equivalent, please see this:
[https://github.com/boluoweifenda/WAGE/blob/master/source/Quantize.py#L42](url)

**Comment by jxgu1016** [comment]
Thx for your quick reply, but I am still confused. Please point it out if I am wrong:
In eq5, **L** is always greater than or equal to **L_min**, so **Shift(L_min/L)** must be no more than 1 and this will set **alpha** to 1.

**Comment by boluoweifenda** [comment]
@jxgu1016 
Please refer to eqn 4:
Shift() function just calculates the factor, and this factor is divided in latter formulation.
Eg:
     Shift(4) equals to 4, not  1
So in equation 6, alpha is always greater than 1

**Comment by jxgu1016** [comment]
What about **Shift(L_min/L)** when L_min<=L?

**Comment by boluoweifenda** [comment]
@jxgu1016 
Then Shift(L_min/L) will smaller than 1.
This situation rarely occurs in low bitwidth representation. 
If n_in equals to 100, and beta*sigma = L_min < L = sqrt(6/100), then sigma < 0.24 => kW > 3.
Since we use ternary weights, L_min is always larger than L (except for the first layer)

**Comment by jxgu1016** [comment]
But the eq5 makes sure that L is not less than L_min and how could this happen?

> Since we use ternary weights, L_min is always larger than L (except for the first layer)

**Comment by boluoweifenda** [comment]
@jxgu1016 
That's why we use max{ } operation in eqn5 and explicitly enlarge L to the value of L_min, which is a
minimum value the uniform distribution U should reach.
Could you please, read section 3.2 ?

**Comment by jxgu1016** [comment]
Sorry to keep disturbing you, but I have already read the whole paper carefully for many times.
Here is my confusion:
L=max(sqrt(6/n_in), L_min) 
==>> L>=L_min 
==>> Shift(L_min/L)<=1
==>> alpha = 1

**Comment by boluoweifenda** [comment]
@jxgu1016 
Oh I see, the eqn6 should be alpha = max{Shift(Lmin/sqrt(6/n_in))}, since the L has been scaled to L_min in eqn 5. It is a typo. You can refer to the code [https://github.com/boluoweifenda/WAGE/blob/master/source/myInitializer.py#L106](url)
Thank you for catching that ! It is very helpful.

**Comment by jxgu1016** [comment]
I have already checked the codes and it is consistent with your modification. 
Grad to find this typo!

**Comment by jxgu1016** [comment]
Besides, I have some questions on my research which I want to discuss about beyond the issue board and could you contact me and give your suggestions via the email on my profile.

**Comment by boluoweifenda** [comment]
@jxgu1016 
Sorry, I have missed your last message, it has been a year.......
Please contact me if you still have any question or need help, my email has been updated into the profile.
